name: missing_plugin_exception_detective
description: "A developer productivity tool that automatically detects, analyzes, and resolves Flutter plugin initialization issues (e.g., MissingPluginException)."
version: 0.1.0
homepage: https://github.com/shariaralphabyte/missing_plugin_exception_detective
repository: https://github.com/shariaralphabyte/missing_plugin_exception_detective
issue_tracker: https://github.com/shariaralphabyte/missing_plugin_exception_detective/issues
documentation: https://pub.dev/documentation/missing_plugin_exception_detective/latest/

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  yaml: ^3.1.2
  path: ^1.8.3
  args: ^2.4.2
  meta: ^1.9.1
  collection: ^1.17.2
  stack_trace: ^1.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.24.6
  mockito: ^5.4.2
  build_runner: ^2.4.7
  coverage: ^1.6.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.shariar99.missing_plugin_exception_detective
        pluginClass: MissingPluginExceptionDetectivePlugin
      ios:
        pluginClass: MissingPluginExceptionDetectivePlugin
      windows:
        pluginClass: MissingPluginExceptionDetectivePluginCApi

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
